### ISSUE TITLE
Can't run composer require openxbl/openxbl 

### ISSUE THREAD

**Issue by vikash12345** [OpenXBL/OpenXBL-PHP#1]
Hello All,

I would like to connect APi of XBL.io
I have downloaded this whole repository from that URL -> https://github.com/OpenXBL/OpenXBL-PHP.git and paste in my www directory then I downloaded composer from that url https://getcomposer.org/
Then I open the “CMD” with same path where I paste repository files which I pasted in www directory
Then I’m running command in cmd “composer require openxbl/openxbl” But its showing above mentioned errors
Please check and give me proper solution.
you can also add me in skype for the solution my skype name is vikashharjeewan2@hotmail.com
I m waiting for your response 
Thanks and Regards
Vikash
![image](https://user-images.githubusercontent.com/19326639/42159497-6cb1678c-7e0d-11e8-906d-a0b678db5e9e.png)

**Comment by dregimbal1** [comment]
This is a composer error - as it states, the version of openxbl could not be found to match your minimum-stability which is set to stable.

In place of 'dev-master' you could use * or in composer.json you could include:
`{
    "minimum-stability": "dev",
    "prefer-stable": true
}`
