### ISSUE TITLE
Unable to get Player Achievements for Xbox 360 Games, empty response- /achievements/player/{xuid}/title/{titleid}

### ISSUE THREAD

**Issue by GeorgeXCV** [OpenXBL/OpenXBL-PHP#2]
`/achievements/player/{xuid}/title/{titleid} `

The above request works perfectly fine for Xbox One games. However, if I use an Xbox 360 Title ID, the response is:
```
{
    "achievements": [],
    "pagingInfo": {
        "continuationToken": null,
        "totalRecords": 0
    }
}
```

**Comment by attheshow** [comment]
I'm getting the same thing for an iOS title that has Xbox Live achievements.

**Comment by GeorgeXCV** [comment]
I recommend joining the Discord, more responsive https://discordapp.com/channels/310973589178417153/310973589178417153.

**Comment by LucienHH** [comment]
> `/achievements/player/{xuid}/title/{titleid} `
> 
> The above request works perfectly fine for Xbox One games. However, if I use an Xbox 360 Title ID, the response is:
> 
> ```
> {
>     "achievements": [],
>     "pagingInfo": {
>         "continuationToken": null,
>         "totalRecords": 0
>     }
> }
> ```

The Official Xbox Live API has a header called x-xbl-contract-version which as far as I know allows you to access different forms of data from the same endpoint. With the achievements endpoint using version 4 will return current gen titles whereas using version 3 will return old-gen titles, unfortunately, it looks like that with the xbl.io API you can't actually specify which version you want to use, I may be wrong.

**Comment by GeorgeXCV** [comment]
> 
> 
> > `/achievements/player/{xuid}/title/{titleid} `
> > The above request works perfectly fine for Xbox One games. However, if I use an Xbox 360 Title ID, the response is:
> > ```
> > {
> >     "achievements": [],
> >     "pagingInfo": {
> >         "continuationToken": null,
> >         "totalRecords": 0
> >     }
> > }
> > ```
> 
> The Official Xbox Live API has a header called x-xbl-contract-version which as far as I know allows you to access different forms of data from the same endpoint. With the achievements endpoint using version 4 will return current gen titles whereas using version 3 will return old-gen titles, unfortunately, it looks like that with the xbl.io API you can't actually specify which version you want to use, I may be wrong.

Thanks, yeah I doubt its an issue on Microsoft's end. My workaround has been using [this](https://xapi.us/) API for 360 titles, although its not ideal because the rate limits are lower.

**Comment by attheshow** [comment]
Looks like this API might not work for my needs then if it doesn't support older games. Thanks for the suggestions!

**Comment by LucienHH** [comment]
You could also try checking out this [repo](https://github.com/XboxReplay/xboxlive-api) which is a wrapper for the official API, so no need to worry about being tied to only a handful of request. It also shows you how to authenticate your own requests. If you need any help give me a shout.

**Comment by GeorgeXCV** [comment]
> 
> 
> You could also try checking out this [repo](https://github.com/XboxReplay/xboxlive-api) which is a wrapper for the official API, so no need to worry about being tied to only a handful of request. It also shows you how to authenticate your own requests. If you need any help give me a shout.

I can't use the official API as you have to be a Xbox Developer to be granted access.

**Comment by LucienHH** [comment]
> > You could also try checking out this [repo](https://github.com/XboxReplay/xboxlive-api) which is a wrapper for the official API, so no need to worry about being tied to only a handful of request. It also shows you how to authenticate your own requests. If you need any help give me a shout.
> 
> I can't use the official API as you have to be a Xbox Developer to be granted access.

If you check out the package it will show you how to self authenticate without using Xbox App authentication.

**Comment by GeorgeXCV** [comment]
> 
> 
> > > You could also try checking out this [repo](https://github.com/XboxReplay/xboxlive-api) which is a wrapper for the official API, so no need to worry about being tied to only a handful of request. It also shows you how to authenticate your own requests. If you need any help give me a shout.
> > 
> > 
> > I can't use the official API as you have to be a Xbox Developer to be granted access.
> 
> If you check out the package it will show you how to self authenticate without using Xbox App authentication.

All I see is this which doesn't work as expected (presumably has to be approved by Microsoft):
```
import XboxLiveAuth from '@xboxreplay/xboxlive-auth';

XboxLiveAuth.authenticate('xbl-account@your-domain.com', '*********')
    .then(console.info)
    .catch(console.error);
```

**Comment by LucienHH** [comment]
You may have to check your accounts sign in history and authorise the location

**Comment by GeorgeXCV** [comment]
> 
> 
> You may have to check your accounts sign in history and authorise the location

Got it working, thanks. I didn't realise its asking for **Xbox Live Account Email Address**. Now to see what I can do with the API, maybe my project isn't dead after all 😄

**Comment by dregimbal1** [comment]
> Looks like this API might not work for my needs then if it doesn't support older games. Thanks for the suggestions!

OpenXBL does have support for Xbox 360 titles. 

For support with how to use the service please join our [Discord channel](https://discord.gg/x6kk8M2).

Closing this issue as it has been a while. Feel free to reopen if there is an issue specifically with this PHP package. Thanks.
