### ISSUE TITLE
Title History endpoint has a limit of 1000 games

### ISSUE THREAD

**Issue by GeorgeXCV** [OpenXBL/OpenXBL-PHP#5]
If profile has more than 1000 games, title history will be wrong because it always stops at #1000. 

Reproduce with request: `https://xapi.us/v2/2533274828276012/title-history`

**Comment by dregimbal1** [comment]
Hi @GeorgeXCV is this still an issue? Please stop by our [Discord channel](https://discord.gg/x6kk8M2) to discuss service-related issues. Thanks
